initial commit

diff --git a/.github/workflows/terraform-apply.yml b/.github/workflows/terraform-apply.yml
--- a/.github/workflows/terraform-apply.yml
+++ b/.github/workflows/terraform-apply.yml
@@ -15,6 +15,13 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - uses: hashicorp/setup-terraform@v3
+      - name: Check WIF secrets
+        run: |
+          if [ -z "${{ secrets.WIF_PROVIDER }}" ] || [ -z "${{ secrets.GITHUB_SA }}" ]; then
+            echo "Missing GitHub secrets: WIF_PROVIDER and/or GITHUB_SA"
+            echo "Please add both repository secrets before rerunning the workflow."
+            exit 1
+          fi
       - uses: google-github-actions/auth@v2
         with:
           workload_identity_provider: ${{ secrets.WIF_PROVIDER }}
diff --git a/.github/workflows/terraform-pr.yml b/.github/workflows/terraform-pr.yml
--- a/.github/workflows/terraform-pr.yml
+++ b/.github/workflows/terraform-pr.yml
@@ -25,6 +25,14 @@ jobs:
         with:
           terraform_version: 1.12.2
 
+      - name: Check WIF secrets
+        run: |
+          if [ -z "${{ secrets.WIF_PROVIDER }}" ] || [ -z "${{ secrets.GITHUB_SA }}" ]; then
+            echo "Missing GitHub secrets: WIF_PROVIDER and/or GITHUB_SA"
+            echo "Please add both repository secrets before rerunning the workflow."
+            exit 1
+          fi
+
       - name: Authenticate to GCP
         uses: google-github-actions/auth@v2
         with:
